name: Linux-VPS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
#    - name: If failed, means ok
#      run: ./not-exist-file.sh it bloke build
    - name: Preparando el sistema linux.
      run: sudo apt-get update
    - name: Instalando el sistema linux.
    #  if: ${{ failure() }}
      run: bash linux-ssh.sh
      env:
        LINUX_USER_PASSWORD: ${{ secrets.LINUX_USER_PASSWORD }}
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        CHROME_HEADLESS_CODE: ${{ secrets.CHROME_HEADLESS_CODE }}
        LINUX_MACHINE_NAME: ${{ secrets.LINUX_MACHINE_NAME }}
        LINUX_USERNAME: ${{ secrets.LINUX_USERNAME }}
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        
    - name: Configurar github.
    # if ${{ failure() }}
      run: git config --global user.email "${{ secrets.GIT_EMAIL }}" && git config --global user.name "${{ secrets.GIT_NAME }}"
           
    - name: Seguir corriendo el sistema linux y dejalo por 6 horas.
     # if: ${{ failure() }}
      run: sleep 6h
